#!/usr/bin/env python3
"""Compute the source and launcher digests needed by a Leo2 release manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import zipfile
from pathlib import Path


def _tree_digest(root: Path) -> tuple[int, str]:
    """Hash a checkout tree while rejecting symlinks and generated bytecode."""
    if root.is_symlink() or not root.is_dir():
        raise ValueError(f"source root is missing or symbolic: {root}")
    links = [path for path in root.rglob("*") if path.is_symlink()]
    if links:
        raise ValueError("source tree contains symbolic links:\n  " + "\n  ".join(map(str, links)))
    files = [
        path
        for path in root.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc"
    ]
    digest = hashlib.sha256()
    for path in sorted(files, key=lambda item: item.relative_to(root).as_posix()):
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
        digest.update(b"\0")
    return len(files), digest.hexdigest()


def _wheel_digest(wheel: zipfile.ZipFile, prefix: str) -> tuple[int, str]:
    """Hash one wheel subtree with the installed-runtime algorithm."""
    names = [
        name
        for name in wheel.namelist()
        if name.startswith(prefix)
        and not name.endswith("/")
        and "/__pycache__/" not in name
        and not name.endswith(".pyc")
    ]
    if len(names) != len(set(names)):
        raise ValueError(f"wheel contains duplicate entries below {prefix}")
    digest = hashlib.sha256()
    for name in sorted(names):
        digest.update(name.removeprefix(prefix).encode())
        digest.update(b"\0")
        digest.update(hashlib.sha256(wheel.read(name)).digest())
        digest.update(b"\0")
    return len(names), digest.hexdigest()


def _regular_digest(repo: Path, relative: str) -> str:
    """Hash one required non-symbolic checkout file."""
    path = repo / relative
    if path.is_symlink() or not path.is_file() or not path.resolve().is_relative_to(repo):
        raise ValueError(f"required checkout file is missing, unsafe or symbolic: {path}")
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    """Print the manifest contract for one checkout and optional wheel."""
    default_repo = Path(__file__).resolve().parents[4]
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=default_repo)
    parser.add_argument("--wheel", type=Path)
    args = parser.parse_args()

    repo = args.repo.resolve()
    unirl_files, unirl_digest = _tree_digest(repo / "unirl")
    leo2_files, leo2_digest = _tree_digest(repo / "unirl/models/leo2")
    contract: dict[str, object] = {
        "checkout_unirl_source_files": unirl_files,
        "checkout_unirl_tree_sha256": unirl_digest,
        "checkout_leo2_source_files": leo2_files,
        "checkout_leo2_tree_sha256": leo2_digest,
        "native_launcher_path": "examples/diffusion/leo2/scripts/native_t2v.sh",
        "native_launcher_sha256": _regular_digest(repo, "examples/diffusion/leo2/scripts/native_t2v.sh"),
        "native_smoke_path": "examples/diffusion/leo2/data/native_smoke.csv",
        "native_smoke_sha256": _regular_digest(repo, "examples/diffusion/leo2/data/native_smoke.csv"),
    }
    if args.wheel is not None:
        with zipfile.ZipFile(args.wheel.resolve()) as wheel:
            installed_files, installed_digest = _wheel_digest(wheel, "unirl/")
            installed_leo2_files, installed_leo2_digest = _wheel_digest(wheel, "unirl/models/leo2/")
        contract.update(
            {
                "installed_unirl_source_files": installed_files,
                "installed_unirl_tree_sha256": installed_digest,
                "leo2_source_files": installed_leo2_files,
                "leo2_tree_sha256": installed_leo2_digest,
            }
        )
    print(json.dumps(contract, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
