#!/usr/bin/env bash
set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_DIR=${LEO2_REPO_DIR:-$(cd "${HERE}/../../../.." && pwd)}
ENV_DIR=${LEO2_ENV_DIR:?set LEO2_ENV_DIR to the installed Leo2 runtime prefix}
PYTHON_BIN=${ENV_DIR}/bin/python
VERIFY_GPU=${LEO2_VERIFY_GPU:-1}
VERIFY_ASSET_CHECKSUMS=${LEO2_VERIFY_ASSET_CHECKSUMS:-1}
RELEASE_MANIFEST=${HERE}/release-manifest-20260904.json

test -x "${PYTHON_BIN}"
test -f "${RELEASE_MANIFEST}"
[[ "${VERIFY_ASSET_CHECKSUMS}" == 0 || "${VERIFY_ASSET_CHECKSUMS}" == 1 ]] \
  || { echo "LEO2_VERIFY_ASSET_CHECKSUMS must be 0 or 1" >&2; exit 2; }
verify_args=()
[[ "${VERIFY_GPU}" == 0 ]] || verify_args+=(--gpu)
"${PYTHON_BIN}" "${HERE}/verify_leo2_runtime.py" "${verify_args[@]}"

PYTHONPATH="${REPO_DIR}" PYTHONNOUSERSITE=1 "${PYTHON_BIN}" \
  - "${REPO_DIR}" "${RELEASE_MANIFEST}" <<'PY'
import hashlib
import json
import sys
from pathlib import Path

repo = Path(sys.argv[1]).resolve()
release = json.loads(Path(sys.argv[2]).read_text())


def source_tree_digest(root: Path) -> tuple[int, str]:
    """Hash path names and contents while excluding generated bytecode."""
    if root.is_symlink() or not root.is_dir():
        raise SystemExit(f"checkout source root is missing or symbolic: {root}")
    links = [path for path in root.rglob("*") if path.is_symlink()]
    if links:
        raise SystemExit("checkout source contains symbolic links:\n  " + "\n  ".join(map(str, links)))
    files = [
        path
        for path in root.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc"
    ]
    digest = hashlib.sha256()
    for path in sorted(files, key=lambda item: item.relative_to(root).as_posix()):
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
        digest.update(b"\0")
    return len(files), digest.hexdigest()


module_root = repo / "unirl"
overlay = release["code_overlay"]
unirl_files, unirl_digest = source_tree_digest(module_root)
leo2_files, leo2_digest = source_tree_digest(module_root / "models" / "leo2")
actual = {
    "checkout_unirl_source_files": unirl_files,
    "checkout_unirl_tree_sha256": unirl_digest,
    "checkout_leo2_source_files": leo2_files,
    "checkout_leo2_tree_sha256": leo2_digest,
}
for key, value in actual.items():
    if value != overlay[key]:
        raise SystemExit(f"checkout {key} mismatch: expected {overlay[key]!r}, got {value!r}")

for path_key, digest_key, label in (
    ("native_launcher_path", "native_launcher_sha256", "native launcher"),
    ("native_smoke_path", "native_smoke_sha256", "native smoke prompt"),
):
    relative = Path(overlay[path_key])
    candidate = repo / relative
    if relative.is_absolute() or ".." in relative.parts or candidate.is_symlink() or not candidate.is_file():
        raise SystemExit(f"{label} is missing, unsafe or symbolic: {candidate}")
    if not candidate.resolve().is_relative_to(repo):
        raise SystemExit(f"{label} escaped checkout: {candidate}")
    digest = hashlib.sha256(candidate.read_bytes()).hexdigest()
    if digest != overlay[digest_key]:
        raise SystemExit(f"{label} digest mismatch: expected {overlay[digest_key]}, got {digest}")

sys.path.insert(0, str(repo))
import unirl
from unirl.models.leo2 import Leo2PipelineConfig

imported_root = Path(unirl.__file__).resolve().parent
if imported_root != module_root:
    raise SystemExit(f"UniRL import escaped checkout: {imported_root}")
required = {
    "inference_cache_method",
    "inference_cache_taylor_max_extrapolation",
    "inference_cache_magcache_max_skip_steps",
    "inference_cache_fastercache_interval",
}
missing = required - Leo2PipelineConfig.__dataclass_fields__.keys()
if missing:
    raise SystemExit(f"Leo2 checkout lacks cache fields: {sorted(missing)}")
print(
    f"Leo2 checkout contract passed: unirl_files={unirl_files}, "
    f"leo2_files={leo2_files}, launcher={overlay['native_launcher_path']}"
)
PY

: "${LEO2_CKPT_DIR:?source leo2-assets.env before running the doctor}"
: "${LEO2_ASSETS_BASE:?source leo2-assets.env before running the doctor}"
if [[ "${VERIFY_ASSET_CHECKSUMS}" == 1 ]]; then
  PYTHONPATH="${REPO_DIR}" PYTHONNOUSERSITE=1 "${PYTHON_BIN}" \
    -m unirl.models.leo2.verify_artifacts --require-checksums
else
  echo "warning: artifact SHA-256 verification skipped; checking layout only" >&2
  PYTHONPATH="${REPO_DIR}" PYTHONNOUSERSITE=1 "${PYTHON_BIN}" - <<'PY'
from unirl.models.leo2 import Leo2PipelineConfig

config = Leo2PipelineConfig()
print(f"Leo2 artifact layout-only check passed: checkpoint={config.ckpt_path}, assets={config.assets_base}")
PY
fi

if [[ "${LEO2_DEEPEP_8RANK:-0}" == 1 ]]; then
  TRMT_LOG_ENABLE=false NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}" \
    "${PYTHON_BIN}" -m torch.distributed.run --standalone --nnodes=1 --nproc_per_node=8 \
    "${HERE}/deepep_8rank_smoke.py"
fi
